# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - streamcricket

on:
  push:
    branches:
      - feat-unnecessary-devops
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_c9ab0cafe14644a1b84386bc2e0bb987 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_e8707ae32da74be38485f97c09263797 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c9ab0cafe14644a1b84386bc2e0bb987 }}/streamrcricket:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'streamcricket'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_aa5542701c7845edb6d86e24a6a602b0 }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c9ab0cafe14644a1b84386bc2e0bb987 }}/streamrcricket:${{ github.sha }}'
